@startuml
title KSR_Ling_Class_diagram_ling



class Summary{
    - String summary
    - List<Double> measures
}
/'
interface LingSummary{
    Summary getFirstFormSummary(List<FoodItem>)
    Summary getSecondFormSummary(List<FoodItem>, FuzzySet)
    getThirdFormSummary(List<FoodItem>, FuzzySet)
    getFourthFormSummary(List<FoodItem>, FuzzySet)
}


class SingleSummary implements LingSummary{
    - LingQuantifier lingQuantifier
    - FuzzySet fuzzySet
}

class CompoundSummary{
    - List<LingQuantifier> lingQuantifier
    - FuzzySet fuzzySet
    Summary getThirdFormSummary(FuzzySet secondSet)
}
'/
class LingQuantifier{
    - String name
    - MemberFunc mamberFunc
    - boolean isAbsolute
    double getValue(double)
}

class Summarizer{
    - List<FuzzySet> fuzzySets
    - List<Boolean> setAnd
    - List<FuzzySet> divisors
    - List<Boolean> divisorAnd
    - LingQuantifier lingQuantifier

    void addFuzzySet(FuzzySet, boolean)
    void addDivisor(FuzzySet, boolean)
    double DoM(FoodItem, boolean)
    double cardinality(List<FoodItem>)
    double divisorCardinality(List<FoodItem>)
    List<FoodItem> summarizedSupport(List<FoodItem>)
    int summarizedSupportCount(List<FoodItem>)
    Summary constructSummary(List<FoodItem>)
}

class QualityMeasure{
    - static double T1(Summarizer summarizer, List<FoodItem> foodItems)
    - static double T2(Summarizer summarizer, List<FoodItem> foodItems)
    - static double T3(Summarizer summarizer, List<FoodItem> foodItems)
    - static double T4(Summarizer summarizer, List<FoodItem> foodItems)
    - static double T5(Summarizer summarizer, List<FoodItem> foodItems)
    - static double optimalSummaryMetric(Summarizer, List<FoodItem>, List<Double>)
    - static double T6(Summarizer summarizer, List<FoodItem> foodItems)
    - static double T7(Summarizer summarizer, List<FoodItem> foodItems)
    - static double T8(Summarizer summarizer, List<FoodItem> foodItems)
    - static double T9(Summarizer summarizer, List<FoodItem> foodItems)
    - static double T10(Summarizer summarizer, List<FoodItem> foodItems)
    - static double ExtendedOptimalSummaryMetric(Summarizer summarizer, List<FoodItem> foodItems, List<Double>)
    List<double> getMeasures()
}


Summarizer *-- Summary
Summarizer ..> QualityMeasure
Summarizer o-- LingQuantifier
/'
LingSummary o-- Summary
SingleSummary o-- LingQuantifier
CompoundSummary o-- LingQuantifier
'/