@startuml
title KSR_Ling_Class_diagram_fuzzy

class FoodItem{
    - String name
    - int calories
    - float fat
    - float protein
    - float carbohydrates
    - float saturatedFats
    - float calcium
    - float iron
    - float water
    - float phosphorus
    - float sodium

    double getProperty(Field)
}

class SubFunc{
    - float start
    - float end
    - Experssion func
    - Argument arg

    double getValue(float)
    double getIntegral()

}

class MemberFunc{
    - List<subFunc> subFuncList
    double getValue(double)
}

class LingVariable{
    - String name
    - Field foodProperty
    - List<String> values
    - List<MemberFunc> memberFuncList

    double getFuncValue(String, double)
    MemberFunc getMemberFunc(String)
    SubFunc getSubFunc(String, double)
}

class FuzzySet{
    - LingVariable variable
    - String value

    double DoM(FoodItem foodItem)
    double cardinality(list<FoodItem>)
    List<FoodItem> support(list<FoodItem>)
    int height(list<FoodItem>)
    List<FoodItem> alphaCut(List<FoodItem>, float)
    int alphaCutHeight(List<FoodItem>, float)
    List<FoodItem> complement(List<FoodItem>)
    boolean isNormal(List<FoodItem>)
    boolean isEmpty(List<FoodItem>)
    boolean isConvex(List<FoodItem>)
    boolean isConcave(List<FoodItem>)
    FuzzySet setUnion(FuzzySet)
    FuzzySet setIntersect(FuzzySet)
}

MemberFunc *-- SubFunc
FuzzySet --> FoodItem
FuzzySet ..> LingVariable
LingVariable *-- MemberFunc



